services:
  - type: web
    name: maya-croche-api
    runtime: docker
    dockerfilePath: ./dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: CORS_ORIGIN
        value: https://maya-croche-frontend.vercel.app
      - key: ADMIN_SEED_NAME
        sync: false
      - key: ADMIN_SEED_EMAIL
        sync: false
      - key: ADMIN_SEED_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
